### ISSUE TITLE
trouble running SCAFFoLD analysis

### ISSUE THREAD

**Issue by CNicholasMDA** [nolanlab/scaffold#13]
Hi,
My team is having trouble running the SCAFFoLD package in R.  We are using R Studio 3.4.4.
The GUI returns a successful completion message, but the warning message in R Studio is:

Warning in parallel::mclapply(files.list, mc.cores = num.cores, mc.preschedule = FALSE,  :
  21 function calls resulted in an error

Is this an issue with the SCAFFoLD package, the Bioconductor packages, or something else?
Thank you!
-Courtney

**Comment by CNicholasMDA** [comment]
Update: still no success.
I reinstalled all associated packages and this is what I am running so far:
R Console version 3.4.4
FlowCore from Bioconductor version 3.6 (BiocInstaller 1.28.0)
devtools from CRAN (revolutionanalytics.com)
install_github("nolanlab/scaffold")
running all in a Mac OS environment, with C++ compiler (XCode) installed...


also getting same error using grappolo, unfortunately

**Comment by pfgherardini** [comment]
Please post this issue in the grappolo package, because that is what I am mantaining right now. Also please include data to reproduce the problem, and the exact code you are running. I suspect this is a problem with the way you are configuring the analysis
