### ISSUE TITLE
Problem with first step of SCAFFOLD

### ISSUE THREAD

**Issue by AbbyKimball** [nolanlab/scaffold#14]
Hello,

I was trying to get SCAFFOLD to work again, but I'm still having issues. I have selected FCS files after entering the command "scaffold.run()", but when SCAFFOLD window opens on Chrome I can't select anything and thus can't run the analysis. Is anyone else having issues with the newest version of R? I was able to get a bit further into the analysis without running into problems on the previous version.

Thanks

**Comment by pfgherardini** [comment]
Hi,

As discussed in the README (https://github.com/nolanlab/scaffold/blob/master/README.md) there is a new version of the whole data analysis pipeline that has much better capabilities. Please try to use that version and post an issue in one of the other packages if you still have problems.

Thanks

Federico

**Comment by AbbyKimball** [comment]
I'm a little lost looking over these new packages. Do you propose you upload your FCS files into Grappolo and then upload the RDS file generated from Gappolo to Vite for visualization? 

An explicit step by step guide (similar to what our lab has [done](http://www.jimmunol.org/content/200/1/3) for other clustering algorithms) is really necessary for bench scientists with little to moderate computer science knowledge to use these tools. I'd love to use SCAFFOLD, but I have been unsuccessful with the current documentation provided.

Thanks.

**Comment by pfgherardini** [comment]
Hi Abby. Yes in a nutshell that is what you would do. We put together a comprehensive tutorial that shows an end-to-end analysis here.

https://github.com/ParkerICI/flow-analysis-tutorial

Hopefully this should address most of your questions. If something is unclear please open an issue on the tutorial repository and I'd be happy to modify accordingly
